export const funQuotes = [
    (n: string) => `Hey ${n}, coffee first, logic later.`,
    (n: string) => `Hello ${n}, emails won’t reply themselves.`,
    (n: string) => `Hi ${n}, meetings survived — now work.`,
    (n: string) => `Welcome ${n}, productivity mode ON.`,
    (n: string) => `Hey ${n}, your chair missed you.`,
    (n: string) => `Hello ${n}, one task at a time.`,
    (n: string) => `Hi ${n}, inbox looks manageable… maybe.`,
    (n: string) => `Welcome ${n}, fewer tabs today.`,
    (n: string) => `Hey ${n}, focus beats chaos.`,
    (n: string) => `Hello ${n}, let’s keep it clean.`,
    (n: string) => `Hi ${n}, calm mind, clear work.`,
    (n: string) => `Welcome ${n}, do the important things first.`,
    (n: string) => `Hey ${n}, one break earned later.`,
    (n: string) => `Hello ${n}, keyboard ready.`,
    (n: string) => `Hi ${n}, let’s survive today productively.`,
    (n: string) => `Welcome ${n}, work smart.`,
    (n: string) => `Hey ${n}, deadlines can wait a second.`,
    (n: string) => `Hello ${n}, progress loading.`,
    (n: string) => `Hi ${n}, today looks workable.`,
    (n: string) => `Welcome ${n}, no rush — just focus.`,
    (n: string  ) => `Hey ${n}, breathe and begin.`,
    (n: string) => `Hello ${n}, dashboard says hello.`,
    (n: string) => `Hi ${n}, fewer distractions today.`,
    (n: string) => `Welcome ${n}, keep it simple.`,
    (n: string) => `Hey ${n}, ready when you are.`,
  ];
  