import { create } from "zustand";

import { SalesOfferInterface } from "@/util/type";

export const useSalesOfferStore = create<SalesOfferInterface>((set) => ({
  phoneNumber: "",
  leadStatus: "",
  note: "-",
  name: "-",
  propertyName: "-",
  relation: "-",
  email: "xyz@gmail.com",
  propertyUrl: "-",
  services: "-",
  country: "-",
  state: "-",
  city: "-",
  plan: "-",
  discount: 0,
  effectivePrice: 0,
  expiryDate: null,
  callBackDate: null,
  callBackTime: null,
  availableOn: [],
  platform: "TechTunes",
  setField: (field, value) => set((state) => ({ ...state, [field]: value })),
  resetForm: () =>
    set({
      phoneNumber: "",
      leadStatus: "",
      note: "-",
      name: "-",
      propertyName: "-",
      relation: "-",
      email: "xyz@gmail.com",
      propertyUrl: "-",
      services: "-",
      country: "-",
      state: "-",
      city: "-",
      plan: "-",
      discount: 0,
      effectivePrice: 0,
      expiryDate: null,
      callBackDate: null,
      callBackTime: null,
      availableOn: [],
      platform: "VacationSaga",
    }),
}));
