import { z } from "zod";

export const employeeSchema = z.object({
  name: z.string().min(1, "Please enter your name"),
  email: z.string().email("Please enter a valid email address"),
  profilePic: z.string().optional().default(""),
  sendDetails: z.boolean().optional().default(false),
  nationality: z.string().min(1, "Please enter your nationality"),
  gender: z.enum(["Male", "Female", "Other"]),
  spokenLanguage: z.string().min(1, "Please Enter the language "),
  bankDetails: z.string().optional(),
  accountNo: z.string().min(1, "Please enter your AccountNo"),
  ifsc: z.string().min(1, "Please enter your IFSC code"),
  aadhar: z.string().min(1, "Please enter your Aadhar number"),
  dateOfJoining: z.date(),
  experience: z.number().optional().default(2),
  alias: z.string().min(1, "Please enter your Alias").optional(),
  phone: z.string().min(1, "Phone number is required"),
  myRequests: z.array(z.string()).optional(),
  myUpcommingRequests: z.array(z.string()).optional(),
  declinedRequests: z.array(z.string()).optional(),
  country: z.string().min(1, "Please enter your country"),
  address: z.string().min(1, "Address is required"),
  password: z.string().min(1, "Please enter your password"),
  isVerified: z.boolean().optional().default(false),
  role: z.enum([
    "Owner",
    "Traveller",
    "Admin",
    "Advert",
    "Content",
    "Sales",
    "HR",
  ]),
  forgotPasswordToken: z.string().optional(),
  forgotPasswordTokenExpiry: z.date().optional(),
  verifyToken: z.string().optional(),
  verifyTokenExpiry: z.date().optional(),
  otpToken: z.number().optional(),
  otpTokenExpiry: z.date().optional(),
});

export type EmployeeSchema = z.infer<typeof employeeSchema>;
